# Generated by Django 4.2.11 on 2024-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_namber', models.CharField(max_length=15)),
                ('invite_code_active', models.CharField(max_length=6)),
                ('invite_code_personal', models.CharField(max_length=6)),
            ],
        ),
    ]
