# Generated by Django 4.2.11 on 2024-04-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_namber',
            new_name='phone_number',
        ),
    ]
